# name = 10
# print(type(name))

# int - integer = целые число 
# str - string = строка обозначается "", ''
# float - цисло с остатками 
# bool - boolean - True, False логический тип данных 
# list - [] изменяемый тип данны
# tuple - () неизменяемый тип данны
# dict - {} ключ и значение
# set - удляет дубликаты изменяемый
# frozenset - множкство не изменяемый

# while True: бесконечный цикл 

# for i in range: цикл 
 
# def hello():
#     name = 10
#     print(name)
# hello()

#f строка ето строковые литералы